version: '3'
networks:
  vorlonjs:
    driver: overlay
services:
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:1.13
    networks:
      - vorlonjs
    environment:
      DF_NOTIFY_CREATE_SERVICE_URL: http://proxy:8080/v1/docker-flow-proxy/reconfigure
      DF_NOTIFY_REMOVE_SERVICE_URL: http://proxy:8080/v1/docker-flow-proxy/remove
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  proxy:
    image: vfarcic/docker-flow-proxy:1.200
    networks:
      - vorlonjs
    environment: 
      MODE: swarm
      LISTENER_ADDRESS: swarm-listener
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
  govorlonjs:
    image: vorlonjs/govorlonjs:0.5.4-dev
    networks:
      - vorlonjs
    environment: 
      VORLONJS_API_KEY: "YOUR_API_KEY"
      VORLONJS_API_SECRET: "YOUR_API_SECRET"
    ports: 
      - "82:82"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
        com.df.notify: true
        com.df.distribute: true
        com.df.servicePath: "/api"
        com.df.port: 82